export { P4Client } from "./client.js";
export {
  P4CommandError,
  P4TimeoutError,
  classifyP4Error,
  isP4ConnectionError
} from "./errors.js";
export type { P4ErrorCategory } from "./errors.js";
export {
  createP4Service,
  describeChangelist,
  diffFile,
  getChangelistDiffSummary,
  getChangelistFiles,
  getP4Environment,
  getOpenedFiles,
  listChangelists,
  listPendingChangelists,
  listP4Workspaces,
  listShelvedChangelists,
  listSubmittedChangelists,
  previewReconcile,
  printFile,
  setClient,
  streamPreviewReconcile,
  streamSync,
  switchWorkspace,
  previewSync,
  sync
} from "./service.js";
export {
  mergeIncompleteSettings,
  parseP4SetOutput,
  parseP4vApplicationSettingsXml,
  parseP4vConnectionMapXml,
  parseP4vConnectionString,
  parseRegQueryOutput,
  resolveP4Settings,
  resolveP4SettingsWithDetails
} from "./settings.js";
export {
  buildDepotDiffFilespec,
  isBinaryP4Type,
  isLocalWorkspace,
  normalizeNullableNumber,
  normalizeNullableString,
  normalizeP4Change,
  parseP4JsonLines,
  parseP4PrintHeader,
  parseP4ProgressLine,
  parseP4KeyValueOutput,
  parseUnifiedDiff,
  resolveDepotDiffRevisions,
  resolveDiffPlan,
  resolveShelvedDiffRevisions,
  summarizeUnifiedDiff,
  unixSecondsToIsoString,
  requireWorkspaceStreamFileSpec,
  workspaceRootFileSpec,
  workspaceStreamFileSpec
} from "./helpers.js";
export type { ResolvedDiffPlan } from "./helpers.js";
export type {
  DescribeChangelistOptions,
  DiffFileOptions,
  GetChangelistDiffSummaryOptions,
  GetEnvironmentOptions,
  GetOpenedFilesOptions,
  ListChangelistsOptions,
  ListChangelistsResult,
  ListWorkspacesOptions,
  ListPendingChangelistsOptions,
  ListShelvedChangelistsOptions,
  ListShelvedChangelistsResult,
  ListSubmittedChangelistsOptions,
  ListSubmittedChangelistsResult,
  LocalWorkspaceCandidate,
  P4ChangelistListSummary,
  P4ChangelistListStatus,
  P4ChangelistDescription,
  P4ChangelistDiffFileSummary,
  P4ChangelistDiffSummary,
  P4CliSettings,
  P4CommandExecutor,
  P4CommandOptions,
  P4CommandResult,
  P4CommandStreamEvent,
  P4CommandStreamSource,
  P4DescribedFile,
  P4DiffHunk,
  P4DiffSource,
  P4EnvironmentSummary,
  P4FileDiffResult,
  P4JsonValue,
  P4JsonWorkspace,
  P4ListWorkspaceResult,
  P4OperationHandle,
  P4OpenedFileSummary,
  P4PendingChangelistSummary,
  P4PrintResult,
  P4ResolvedSettings,
  P4ReconcileCandidate,
  P4ReconcileProgressEvent,
  P4ReconcilePreviewResult,
  P4ClientOptions,
  P4ProgressSnapshot,
  P4Service,
  P4SettingKey,
  P4SettingsContribution,
  P4SettingsSource,
  P4StreamingCommandExecutor,
  P4ShelvedChangelistSummary,
  P4SubmittedChangelistSummary,
  P4SyncErrorItem,
  P4SyncItem,
  P4SyncProgressEvent,
  P4SyncResult,
  P4SyncResultWithErrors,
  P4SyncPreviewItem,
  P4SyncPreviewResult,
  P4WorkspaceSummary,
  PreviewReconcileOptions,
  PreviewSyncOptions,
  PrintFileOptions,
  ResolveP4SettingsOptions,
  SetClientOptions,
  SetClientResult,
  SyncOptions,
  RunTaggedJsonOptions,
  WatchP4CommandOptions
} from "./types.js";
